# Generated by Django 2.2.24 on 2021-07-22 21:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 22, 21, 37, 35, 739959, tzinfo=utc)),
        ),
    ]
