# Generated by Django 2.2.24 on 2021-11-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20210722_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='stock',
            field=models.CharField(max_length=2083),
        ),
    ]
