# Generated by Django 2.2.24 on 2021-11-03 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20211103_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='stock',
            new_name='image_url',
        ),
    ]
