# Generated by Django 2.2.24 on 2021-12-02 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20211103_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costumer_name', models.CharField(max_length=125)),
                ('email', models.EmailField(max_length=125)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.IntegerField()),
                ('card_holder', models.CharField(max_length=100)),
                ('card_number', models.IntegerField()),
                ('Exp_month', models.CharField(max_length=25)),
                ('Exp_year', models.DateTimeField()),
                ('CVV', models.IntegerField()),
            ],
        ),
    ]
