# Generated by Django 2.2.24 on 2021-12-02 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='Exp_year',
            field=models.IntegerField(max_length=6),
        ),
    ]
