# Generated by Django 2.2.24 on 2021-12-04 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20211202_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='Exp_year',
            field=models.IntegerField(),
        ),
    ]
