# Generated by Django 2.2.24 on 2021-12-15 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_auto_20211204_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='cash',
            field=models.IntegerField(default=1),
        ),
    ]
